---
galaxy_info:
  author: Guan Guan
  description: Ansible Playframework Playbook Role
  company: http://likeorz.com
  license: Apache 2
  min_ansible_version: 1.7
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  categories:
  - development
dependencies:
  - { role: "ansible-java8-oracle" }